package me.cg360.spudengine.core.render.pipeline.util;

//VK11.VK_BLEND_FACTOR_...
public enum BlendFactor {

    ZERO, ONE,
    SRC_COLOUR, ONE_MINUS_SRC_COLOUR,
    DST_COLOUR, ONE_MINUS_DST_COLOUR,
    SRC_ALPHA,  ONE_MINUS_SRC_ALPHA,
    DST_ALPHA,  ONE_MINUS_DST_ALPHA,
    CONSTANT_COLOUR, ONE_MINUS_CONSTANT_COLOUR,
    CONSTANT_ALPHA,  ONE_MINUS_CONSTANT_ALPHA,
    SRC_ALPHA_SATURATE,
    SRC1_COLOUR, ONE_MINUS_SRC1_COLOUR,
    SRC1_ALPHA,  ONE_MINUS_SRC1_ALPHA;

}
